// Generated by scripts/splitRoutes.js — do not edit manually.
import { type TYPES } from 'src/models';

export const loadRouteChunk = (date: string): TYPES.RawRoute[] => {
  switch (date) {
    case '2026-03-23':
      return require('src/assets/data/routes/2026-03-23.json');
    case '2026-03-24':
      return require('src/assets/data/routes/2026-03-24.json');
    case '2026-03-25':
      return require('src/assets/data/routes/2026-03-25.json');
    case '2026-03-26':
      return require('src/assets/data/routes/2026-03-26.json');
    case '2026-03-27':
      return require('src/assets/data/routes/2026-03-27.json');
    case '2026-03-28':
      return require('src/assets/data/routes/2026-03-28.json');
    case '2026-03-29':
      return require('src/assets/data/routes/2026-03-29.json');
    default:
      return [];
  }
};
