const fs = require('fs');
const path = require('path');

// Mirrors src/constants/scheduleConfig.ts DAYS_ORDER and
// src/utils/scheduleUtils.ts parseSchedule — duplicated here since this
// script runs standalone with plain Node, not the app's TS/module-resolver setup.
const DAYS_ORDER = ['1', '2', '3', '4', '5', '6', '7'];
const parseSchedule = schedule =>
  !schedule || schedule.length < 7
    ? []
    : DAYS_ORDER.filter((day, index) => schedule[index] === day);

const TOP_ADDRESSES_LIMIT = 5;

const sourcePath = path.join(__dirname, 'routes.source.json');
const dataDir = path.join(__dirname, '..', 'src', 'assets', 'data');
const routesDir = path.join(dataDir, 'routes');
const manifestPath = path.join(
  __dirname,
  '..',
  'src',
  'utils',
  'routesManifest.ts',
);

const { routes } = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));

fs.mkdirSync(routesDir, { recursive: true });

const routesByDate = Object.groupBy(routes, route => route.date);
const dates = Object.keys(routesByDate).sort();

dates.forEach(date => {
  fs.writeFileSync(
    path.join(routesDir, `${date}.json`),
    JSON.stringify(routesByDate[date]),
  );
});

fs.writeFileSync(path.join(dataDir, 'routesIndex.json'), JSON.stringify(dates));

const allStops = routes.flatMap(route => route.stops);

const totalStops = allStops.length;
const totalContainers = allStops.reduce((sum, stop) => sum + stop.c, 0);
const totalVolume = allStops.reduce((sum, stop) => sum + stop.v * stop.c, 0);
const uniqueAddresses = new Set(allStops.map(stop => stop.a));

const stopsByDay = DAYS_ORDER.reduce((acc, day) => ({ ...acc, [day]: 0 }), {});
allStops.forEach(stop => {
  parseSchedule(stop.s).forEach(day => {
    stopsByDay[day] += 1;
  });
});

const addressContainers = allStops.reduce((acc, stop) => {
  acc[stop.a] = (acc[stop.a] ?? 0) + stop.c;
  return acc;
}, {});

const topAddresses = Object.entries(addressContainers)
  .sort(([, countA], [, countB]) => countB - countA)
  .slice(0, TOP_ADDRESSES_LIMIT)
  .map(([address, count]) => ({ address, count }));

const routesStats = {
  totalRoutes: routes.length,
  totalDates: dates.length,
  totalStops,
  totalContainers,
  totalVolume,
  uniqueAddresses: uniqueAddresses.size,
  dateRange:
    dates.length > 0 ? `${dates[0]} → ${dates[dates.length - 1]}` : '—',
  stopsByDay,
  maxDayStops: Math.max(...Object.values(stopsByDay), 1),
  topAddresses,
};

fs.writeFileSync(
  path.join(dataDir, 'routesStats.json'),
  JSON.stringify(routesStats),
);

const manifestCases = dates
  .map(
    date =>
      `    case '${date}':\n      return require('src/assets/data/routes/${date}.json');`,
  )
  .join('\n');

const manifestSource = `// Generated by scripts/splitRoutes.js — do not edit manually.
import { type TYPES } from 'src/models';

export const loadRouteChunk = (date: string): TYPES.RawRoute[] => {
  switch (date) {
${manifestCases}
    default:
      return [];
  }
};
`;

fs.writeFileSync(manifestPath, manifestSource);
